#pragma once

#include "VKCmdBeginRenderPass.h"
#include "VKCmdBindDescriptorSets.h"
#include "VKCmdBindIndexBuffer.h"
#include "VKCmdBindPipeline.h"
#include "VKCmdBindVertexBuffers.h"
#include "VKCmdDraw.h"
#include "VKCmdDrawIndexed.h"
#include "VKCmdDrawIndexedIndirect.h"
#include "VKCmdDrawIndirect.h"
#include "VKCmdEndRenderPass.h"
#include "VKCmdPipelineBarrier.h"
#include "VKCmdSetScissor.h"
#include "VKCmdSetViewport.h"